module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: null
cabal-file: project.cabal
modules:
  Network.HTTP.Client.BodySpec:
    filename: test/Network/HTTP/Client/BodySpec.hs
  Network.HTTP.Client.Connection:
    filename: src/Network/HTTP/Client/Connection.hs
  Network.HTTP.Client.ResponseSpec:
    filename: src/Network/HTTP/Client/ResponseSpec.hs
  Network.HTTP.Client.Types:
    filename: src/Network/HTTP/Client/Types.hs
  Network.HTTP.Client.Manager:
    filename: src/Network/HTTP/Client/Manager.hs
  Network.HTTP.Client.Util:
    filename: src/Network/HTTP/Client/Util.hs
  Network.HTTP.Client.HeadersSpec:
    filename: test/Network/HTTP/Client/HeadersSpec.hs
  Network.HTTP.Client.Response:
    filename: src/Network/HTTP/Client/Response.hs
  Spec:
    filename: src/Spec.hs
  Network.HTTP.Client.Headers:
    filename: src/Network/HTTP/Client/Headers.hs
  Network.HTTP.Client.Request:
    filename: src/Network/HTTP/Client/Request.hs
  Network.HTTP.Client.Body:
    filename: src/Network/HTTP/Client/Body.hs
version: 1
ghc-args: []
